Add  tesitng for modify and update
TayyabKM/to-do-list pull request #7
Opened 2022-11-25 04:49 UTC by TayyabKM

3 Tests were created. This tests for:

- editing the task description.
- updating an item's 'completed' status.
- the "Clear all completed" function.

2022-11-25 10:30 UTC, EricMbouwe requested changes
Hi @TayyabKM, 

Good job so far 🔥!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 🔥🎉
- Add test file ✔
- No linter errors ✔

# Required Changes ♻️
- [ ] Installing dependencies is not working. You may check your package.json file and fix it
<img width="863" alt="Screenshot 2022-11-25 at 11 27 33 AM" src="https://user-images.githubusercontent.com/40503704/203963602-a48925eb-fc7f-420e-9b67-9bfe629fb41f.png">

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 12:50 UTC, danielufeli requested changes
Hi @Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors ✔

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 12:50 UTC, danielufeli commented on src/module/toDoDom.js
> +     toDoDom.data('task1', appList);
- [ ] Nice working on your tests, Kindly check it throws the error in the screenshot below when I run the test, 
![image](https://user-images.githubusercontent.com/48371156/203989180-5b54b1b6-82b0-42ca-8ef9-91883579f937.png)

2022-11-26 18:48 UTC, closed without merging

2022-11-26 18:54 UTC, tugsem reviewed
## STATUS: REQUIRED CHANGES ♻️
Hi @TayyabKM and @Itswali , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l2Je9zHYveK012EVi/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-26 18:54 UTC, tugsem commented on src/module/toDoDom.js
> + });
- [ ] As requested by the previous reviewer make sure all of your tests are passing: 
![image](https://user-images.githubusercontent.com/91486791/204104661-3d1772bb-de20-4ade-85b9-709dea0c7cea.png)